version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ make qt4-default'
      - run:
          name: CLEARING Previous Build
          command: 'cd build-GO-Desktop-Debug && make clean'
      - run:
          name: COMPILING CODE
          command: 'cd build-GO-Desktop-Debug && make'
